#define SIGNED_LONGLONG_MIN -9223372036854775807 -1
#define SIGNED_LONGLONG_MAX 9223372036854775807
#define UNSIGNED_LONGLONG_MAX 18446744073709551615

#define SIGNED_LONGLONG_MIN_HEX 0x8000000000000001
#define SIGNED_LONGLONG_MAX_HEX 0x7FFFFFFFFFFFFFFF
#define UNSIGNED_LONGLONG_MAX_HEX 0xffffffffffffffff

#include <stdio.h>
#include <limits.h>

int main()
{
    printf("SIGNED_LONGLONG_MIN : %lld %llu\n", SIGNED_LONGLONG_MIN, SIGNED_LONGLONG_MIN);
    printf("SIGNED_LONGLONG_MAX : %lld %llu\n", SIGNED_LONGLONG_MAX, SIGNED_LONGLONG_MAX);
    printf("UNSIGNED_LONGLONG_MAX : %lld %llu\n", UNSIGNED_LONGLONG_MAX, UNSIGNED_LONGLONG_MAX);

    printf("\n");

    printf("SIGNED_LONGLONG_MIN_HEX : %llx %llx\n", SIGNED_LONGLONG_MIN_HEX, SIGNED_LONGLONG_MIN_HEX);
    printf("SIGNED_LONGLONG_MAX_HEX : %llx %llx\n", SIGNED_LONGLONG_MAX_HEX, SIGNED_LONGLONG_MAX_HEX);
    printf("UNSIGNED_LONGLONG_MAX_HEX : %llx %llx\n", UNSIGNED_LONGLONG_MAX_HEX, UNSIGNED_LONGLONG_MAX_HEX);

    return 0;
}